### ISSUE TITLE
Finding a wpa_cli for devices that works on Android 5.0

### ISSUE THREAD

**Issue by RoundSparrow** [eSoares/Ad-hoc#3]
I'm trying to find a wpa_cli compiled to work on Android 5.0 for devices that don't seem to include it.  I have one that works on 4.4 and earlier, but not compiled for newer PIE.  If anyone knows of one, please let me know.

**Comment by eSoares** [comment]
Indeed, this one is pre 5.0, you should be able to find one compiled version in some custom ROMs from CyanogenMod (CM) or others.
I have a device with me running CM with Android 6.0 and has a compiled version of wpa_cli.
